on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cibuildwheel:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: pypa/cibuildwheel@v2.23
        with:
          package-dir: base
      - uses: pypa/cibuildwheel@v2.23
        with:
          package-dir: my_pkg
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.runs-on }}
          path: ./wheelhouse/*.whl
